import {test,expect} from '@playwright/test';
import {catalogue,dailyPuzzle} from '../src/catalogue';
import type {VPuzzle} from '../src/voxel';
async function solve(page:any,p:VPuzzle){for(const w of p.witness){await page.locator(`[data-item="${w.id}"]`).click();const more=page.locator('.creative-more');await more.evaluate((e:HTMLDetailsElement)=>{e.open=true;});await page.locator(`[data-orientation="${w.orientation}"]`).click();await more.evaluate((e:HTMLDetailsElement)=>{e.open=false;});await page.locator(`[data-cell="${w.at[0]},${w.at[1]}"]`).click();await page.locator('[data-place]').click();}await page.locator('[data-seal]').click();await expect(page.locator('[data-result]')).toBeVisible();}
test('daily solve, share, unlimited next, mode resume and reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await expect(page.locator('[data-item]').first()).toBeVisible();await expect(page).toHaveTitle('Everything Fits packing puzzle');await expect(page.locator('[data-brand]')).toHaveText('Everything Fits');const day=new Date().toISOString().slice(0,10);const p=dailyPuzzle(day);await solve(page,p);await page.locator('[data-share]').click();await expect(page.locator('[data-result-image]')).toHaveJSProperty('naturalWidth',1200);await expect(page.locator('textarea')).toContainText(p.id);await expect(page.locator('textarea')).toHaveValue(/^Everything Fits · Daily\n/);await expect(page.locator('[data-result-image]')).toHaveAttribute('alt',new RegExp('^Everything Fits result for '+p.id));await expect(page.locator('[data-download]')).toHaveAttribute('download',`everything-fits-${p.id}.png`);const downloadPromise=page.waitForEvent('download');await page.locator('[data-download]').click();expect((await downloadPromise).suggestedFilename()).toBe(`everything-fits-${p.id.replaceAll('/','_')}.png`);
 await page.locator('[data-next]').click();await expect(page.locator('[data-mode="Free play"]')).toHaveAttribute('aria-pressed','true');await page.locator('[data-item]').first().click();await page.locator('[data-hint]').click();await expect(page.locator('#packing-hint')).toBeVisible();await page.locator('[data-mode="Daily"]').click();await expect(page.locator('[data-result]')).toBeVisible();await page.locator('[data-mode="Free play"]').click();await expect(page.locator('.creative-clock')).toContainText('+20s');await page.reload();await expect(page.locator('[data-result]')).toBeVisible();await page.locator('[data-mode="Free play"]').click();await expect(page.locator('.creative-clock')).toContainText('+20s');expect(errors).toEqual([]);
});
test('all levels produce actual creative shapes and Expert certified solution',async({page})=>{await page.goto('./');await page.locator('[data-difficulty]').selectOption('Expert');await expect(page.locator('[data-mode="Free play"]')).toHaveAttribute('aria-pressed','true');const title=await page.locator('.creative-heading h1').innerText();const p=catalogue.find(p=>p.title===title&&p.difficulty==='Expert')!;expect(p.certified).toBe(true);expect([1,2]).toContain(p.solutionCount);await solve(page,p);await page.locator('[data-next]').click();await expect(page.locator('.creative-heading h1')).not.toHaveText(title);});
test('mobile usable grid and genuine enlarged text',async({page})=>{await page.setViewportSize({width:360,height:800});await page.goto('./');await expect(page.locator('.creative-grid')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const el of await page.locator('[data-cell]').all()){const b=await el.boundingBox();expect(b!.width).toBeGreaterThanOrEqual(44);expect(b!.height).toBeGreaterThanOrEqual(44);}await page.addStyleTag({content:'html{font-size:200% !important}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('second tab cannot silently overwrite newer progress',async({page,context})=>{await page.goto('./');await expect(page.locator('[data-item]').first()).toBeVisible();const other=await context.newPage();await other.goto('./');await expect(other.locator('[data-item]').first()).toBeVisible();await page.locator('[data-item]').first().click();await page.locator('[data-hint]').click();await other.locator('[data-item]').first().click();await expect(other.getByRole('alert')).toContainText('newer save');await other.close();});

test('one help offer per attempt, free dismissal, timer pause and two hint cap',async({page})=>{const now=new Date();await page.clock.install({time:now});await page.clock.pauseAt(now);await page.setViewportSize({width:360,height:800});await page.goto('./');await expect(page.locator('[data-item]').first()).toBeVisible();await page.clock.runFor(5000);await expect(page.locator('[data-timer]')).toHaveText('0:00');await page.locator('[data-item]').first().click();await page.clock.runFor(61000);await expect(page.locator('.creative-offer')).toBeVisible();const offer=await page.locator('.creative-offer').boundingBox(),grid=await page.locator('.creative-grid').boundingBox();expect(offer!.y+offer!.height).toBeLessThanOrEqual(grid!.y);await page.getByRole('button',{name:'Keep trying'}).click();await expect(page.locator('.creative-clock')).not.toContainText('+20s');const paused=await page.locator('[data-timer]').innerText();await page.locator('[data-mode="Free play"]').click();await page.clock.runFor(10000);await page.locator('[data-mode="Daily"]').click();await expect(page.locator('[data-timer]')).toHaveText(paused);await page.clock.runFor(61000);await expect(page.locator('.creative-offer')).toHaveCount(0);await page.locator('[data-hint]').click();await page.locator('[data-hint]').click();await expect(page.locator('[data-hint]')).toBeDisabled();await expect(page.locator('.creative-clock')).toContainText('+40s');});
