import {test,expect} from '@playwright/test';
import {daily,orientations} from '../src/game';
import {readFile} from 'node:fs/promises';
test('solve daily, save best and download spoiler-free PNG',async({page},testInfo)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const now=new Date();await page.clock.install({time:now});await page.clock.pauseAt(now);await page.goto('./');await expect(page.locator('[data-item]').first()).toBeVisible();await page.clock.runFor(5000);await expect(page.locator('[data-timer]')).toHaveText('0:00');
 const day=(await page.locator('time[datetime]').getAttribute('datetime'))!,p=daily(day);
 await expect(page.locator('.scene canvas')).toBeVisible();await expect(page.locator('[data-seal]')).toHaveCount(0);
 await page.locator('[data-item]').first().click();await page.clock.runFor(5000);await expect(page.locator('[data-timer]')).toHaveText('0:05');await page.locator('[data-hint]').click();await expect(page.locator('#packing-hint')).toContainText('+20s');await page.locator('[data-hint]').click();await expect(page.locator('[data-hint]')).toBeDisabled();await expect(page.locator('#packing-hint')).toContainText('+40s');
 for(const w of p.witness){await page.locator(`[data-item="${w.id}"]`).click();const i=p.items.find(i=>i.id===w.id)!;const turns=orientations(i.dims).findIndex(d=>d.every((v,j)=>v===w.dims[j]));for(let n=0;n<turns;n++)await page.locator('[data-rotate]').click();await page.locator(`[data-cell="${w.at[0]},${w.at[1]}"]`).click();await page.locator('[data-place]').click();}
 await page.clock.runFor(1000);await page.locator('[data-seal]').click();await expect(page.getByText('Completion saved on this device.')).toBeVisible();await page.getByRole('button',{name:'Skip celebration'}).click();const sealed=await page.locator('.scene canvas').screenshot();await page.clock.runFor(1200);expect(sealed.equals(await page.locator('.scene canvas').screenshot())).toBe(true);const frozen=await page.locator('[data-timer]').innerText();await page.clock.runFor(10000);await expect(page.locator('[data-timer]')).toHaveText(frozen);await page.locator('[data-share]').click();
 const image=page.locator('[data-result-image]');await expect(image).toBeVisible();await expect(image).toHaveJSProperty('naturalWidth',1200);await expect(image).toHaveJSProperty('naturalHeight',800);
 await expect(image).toHaveAttribute('alt',/2 hints/);await page.locator('[data-result]').screenshot({path:testInfo.outputPath('finish.png')});await image.screenshot({path:testInfo.outputPath('result-preview.png')});
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-download]').click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe(`everything-fits-${day}.png`);const path=testInfo.outputPath('result.png');await download.saveAs(path);const png=await readFile(path);expect(png.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');expect(png.readUInt32BE(16)).toBe(1200);expect(png.readUInt32BE(20)).toBe(800);
 await page.locator('[data-retry]').click();await page.clock.runFor(5000);await expect(page.locator('[data-timer]')).not.toHaveText(frozen);await expect(page.locator('#packing-hint')).toContainText('+40s');await page.reload();await expect(page.locator('[data-timer]')).toHaveText('0:00');await page.locator('summary').click();await expect(page.getByText('Completed on this device.')).toBeVisible();expect(errors).toEqual([]);
});
test('small screens and corrupt local data remain playable',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:360,height:900});await page.goto('./');await page.evaluate(()=>localStorage.setItem('which-box:daily-practice-v1','[null]'));await page.reload();await expect(page.locator('[data-item]').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('[data-item]').first().click();await expect(page.locator('[data-rotate]')).toBeEnabled();});

test('parcel drop and undo animate, with live reduced motion',async({page})=>{
 const now=new Date();await page.clock.install({time:now});await page.clock.pauseAt(now);await page.goto('./');await expect(page.locator('.scene canvas')).toBeVisible();await page.clock.runFor(1000);
 const p=daily((await page.locator('time[datetime]').getAttribute('datetime'))!),w=p.witness[0],i=p.items.find(i=>i.id===w.id)!;await page.locator('[data-item="'+w.id+'"]').click();const turns=orientations(i.dims).findIndex(d=>d.every((v,j)=>v===w.dims[j]));for(let n=0;n<turns;n++)await page.locator('[data-rotate]').click();await page.locator('[data-cell="'+w.at[0]+','+w.at[1]+'"]').click();await page.clock.runFor(300);
 const canvas=page.locator('.scene canvas');await page.locator('[data-place]').click();await page.clock.runFor(120);const falling=await canvas.screenshot();await page.clock.runFor(500);expect(falling.equals(await canvas.screenshot())).toBe(false);await page.locator('[data-undo]').click();await page.clock.runFor(80);const leaving=await canvas.screenshot();await page.emulateMedia({reducedMotion:'reduce'});await page.clock.runFor(16);const cleared=await canvas.screenshot();expect(leaving.equals(cleared)).toBe(false);await page.clock.runFor(1000);expect(cleared.equals(await canvas.screenshot())).toBe(true);
});

test('camera motion changes frames and reduced motion settles immediately',async({page})=>{
 const now=new Date();await page.clock.install({time:now});await page.clock.pauseAt(now);await page.goto('./');await expect(page.locator('.scene canvas')).toBeVisible();await page.clock.runFor(1000);
 const canvas=page.locator('.scene canvas');const before=await canvas.screenshot();await page.locator('[data-view]').click();await page.clock.runFor(250);const during=await canvas.screenshot();await page.clock.runFor(600);const after=await canvas.screenshot();expect(before.equals(during)).toBe(false);expect(during.equals(after)).toBe(false);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-view]').click();const immediate=await canvas.screenshot();await page.clock.runFor(1000);expect(immediate.equals(await canvas.screenshot())).toBe(true);
});

test('preselection and auto-next reduce clicks; phone controls and enlarged text fit',async({page})=>{
 await page.setViewportSize({width:360,height:800});await page.goto('./');await expect(page.locator('[data-item]').first()).toHaveAttribute('aria-pressed','true');
 const bounds=await page.locator('[data-place]').boundingBox();expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(800);await expect(page.locator('.position-pad')).toBeVisible();await expect(page.locator('[data-box]')).toHaveCount(0);
 const p=daily((await page.locator('time').getAttribute('datetime'))!),w=p.witness[0];await page.locator(`[data-item="${w.id}"]`).click();const i=p.items.find(i=>i.id===w.id)!,n=orientations(i.dims).findIndex(d=>d.every((v,j)=>v===w.dims[j]));for(let k=0;k<n;k++)await page.locator('[data-rotate]').click();await page.locator(`[data-cell="${w.at[0]},${w.at[1]}"]`).click();await page.locator('[data-place]').click();await expect(page.locator(`[data-item="${p.items.find(i=>i.id!==w.id)!.id}"]`)).toHaveAttribute('aria-pressed','true');
 await page.addStyleTag({content:'html{font-size:200% !important}'});expect(await page.locator('[data-item]').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBe(28);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
