import {test} from 'node:test';
import assert from 'node:assert/strict';
import {catalogue,dailyPuzzle} from '../src/catalogue.ts';
import {freshId,chooseNext,cleanAttempt,emptyProgress,newAttempt,restoreProgress} from '../src/progress.ts';
const day=new Date().toISOString().slice(0,10);
test('fresh progress, daily identity and mode attempts are independent',()=>{const p=emptyProgress(),daily=newAttempt(dailyPuzzle(day));p.daily={day,attempt:daily};const choice=chooseNext(p,day,()=>0);assert.ok(choice.puzzle);assert.notEqual(choice.puzzle.id,daily.puzzleId);p.free=newAttempt(choice.puzzle);p.seen.push(choice.puzzle.id);assert.notEqual(chooseNext(p,day,()=>0).puzzle?.id,choice.puzzle.id);assert.equal(p.daily.attempt.attemptId,daily.attemptId);assert.deepEqual(restoreProgress(p),{progress:p,damaged:false});});
test('exhaustion is explicit and never silently repeats a puzzle',()=>{const p=emptyProgress();p.seen=catalogue.map(x=>x.id);assert.equal(chooseNext(p,day).puzzle,null);assert.equal(chooseNext(p,day).exhausted,true);});
test('restored attempts retain time hints and one-shot offer; reject corrupt geometry',()=>{const puzzle=catalogue[0]!,a={...newAttempt(puzzle),placements:puzzle.witness,elapsedMs:1550.25,hints:1,promptOffered:true,started:true,solved:true};assert.deepEqual(cleanAttempt(a),a);assert.equal(cleanAttempt({...a,placements:[{id:'fake',at:[0,0,0],orientation:0}]}),null);assert.equal(cleanAttempt({...a,hints:3}),null);assert.equal(cleanAttempt({...a,elapsedMs:NaN}),null);assert.equal(cleanAttempt({...a,placements:[],solved:true}),null);});
test('invalid progress reported explicitly and completions are bounded',()=>{assert.equal(restoreProgress({version:99}).damaged,true);const p=emptyProgress();p.daily={day,attempt:newAttempt(dailyPuzzle(day))};p.completions=Array.from({length:150},(_,i)=>({puzzleId:catalogue[0]!.id,attemptId:String(i),mode:'Free play' as const,day,hints:0,elapsedMs:0}));assert.equal(restoreProgress(p).progress.completions.length,100);assert.equal(restoreProgress({...p,daily:{day,attempt:newAttempt(catalogue.find(x=>x.id!==dailyPuzzle(day).id)!)}}).damaged,true);});

test('attempt IDs use cryptographic bytes without secure-context randomUUID',()=>{const values=Array.from({length:100},freshId);assert.equal(new Set(values).size,100);for(const value of values)assert.match(value,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);});
