import { useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import { runtime } from './runtime';
import { ResultShare } from './ResultShare';
import { usePackingClock } from './usePackingClock';
import {formatTime,scoredSeconds,HINT_PENALTY_SECONDS} from './timing';
import { Scene } from './Scene';
import { cleanHistory, complete, daily, drop, orientations, utcDay, utilization, validate, volume } from './game';
import type { Placement, Saved } from './game';
const KEY='daily-practice-v1';
export function App(){
 const [day,setDay]=useState(utcDay),puzzle=useMemo(()=>daily(day),[day]);
 const [boxId,setBoxId]=useState('M'),[ps,setPs]=useState<Placement[]>([]),[undo,setUndo]=useState<Placement[][]>([]);
 const [selected,setSelected]=useState<string|null>(null),[orientation,setOrientation]=useState(0),[cell,setCell]=useState<[number,number]>([0,0]);
 const [view,setView]=useState(0),[result,setResult]=useState(false),[hintCount,setHintCount]=useState(0),[tab,setTab]=useState('play');
 const [message,setMessage]=useState('Choose an item. Set its position, rotate, then place it.'),[history,setHistory]=useState<Saved[]>([]),[storage,setStorage]=useState('Loading local results…'),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[share,setShare]=useState(false);
 const clock=usePackingClock(),hint=hintCount>0;
 const [celebrating,setCelebrating]=useState(false);
 useEffect(()=>{if(!celebrating)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const id=setTimeout(()=>setCelebrating(false),reduced?0:1800);return()=>clearTimeout(id);},[celebrating]);
 const snapshot=useRef({});const box=puzzle.boxes.find(b=>b.id===boxId)!,item=puzzle.items.find(i=>i.id===selected),os=item?orientations(item.dims):[],dims=os[orientation%Math.max(1,os.length)];
 const preview=item?drop(item,dims,cell[0],cell[1],ps):null;
 const proposal=preview?[...ps.filter(p=>p.id!==preview.id),preview]:ps;
 const error=preview?validate(puzzle.items,box,proposal):null;
 const packedVolume=ps.reduce((s,p)=>s+volume(p.dims),0),score=utilization(puzzle.items,box),best=history.find(r=>r.id===puzzle.id);
 snapshot.current={puzzleId:puzzle.id,day,box,items:puzzle.items,placements:ps,selected,orientationIndex:orientation,orientedDimensions:dims,preview,error,result,hint,hintCount,elapsedSeconds:clock.elapsed,scoredSeconds:scoredSeconds(clock.elapsed,hintCount),score:result?score:null,storage,localOnly:true};
 useEffect(()=>{runtime.serve({describeView:()=>snapshot.current});runtime.ready();let active=true;runtime.storage.get<unknown>(KEY).then(v=>{if(active){setHistory(cleanHistory(v));setLoaded(true);setStorage('Results stay on this device');}}).catch(()=>{if(active)setStorage('Local storage unavailable. You can still play.');});return()=>{active=false;};},[]);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const update=()=>{const next=utcDay();if(next!==day)setMessage('A new UTC daily order is available. Finish this practice or load today’s order.');timer=setTimeout(update,Math.max(1000,Date.parse(utcDay()+'T00:00:00Z')+86400000-Date.now()+100));};update();return()=>clearTimeout(timer);},[day]);
 function commit(next:Placement[]){setUndo(v=>[...v.slice(-49),ps]);setPs(next);setResult(false);setShare(false);}
 function pick(id:string){if(result)return;clock.begin();setSelected(id);const p=ps.find(p=>p.id===id),i=puzzle.items.find(i=>i.id===id)!;setOrientation(p?Math.max(0,orientations(i.dims).findIndex(d=>d.every((n,j)=>n===p.dims[j]))):0);if(p)setCell([p.at[0],p.at[1]]);}
 function place(){if(!preview||result)return;if(error){setMessage(error);return;}commit(proposal);setSelected(null);setMessage('Placed. Pick another item, or select a packed item to move it.');}
 function remove(){const next=ps.filter(p=>p.id!==selected),issue=validate(puzzle.items,box,next);if(issue){setMessage('This item supports another. Remove the items above it first.');return;}commit(next);setSelected(null);}
 function reset(nextDay=day){setDay(nextDay);setPs([]);setUndo([]);setSelected(null);setResult(false);setHintCount(0);clock.reset();setCelebrating(false);setShare(false);setBoxId('M');setCell([0,0]);setMessage('Choose an item. Set its position, rotate, then place it.');}
 async function seal(){if(!complete(puzzle,box,ps)||busy||result)return;clock.stop();setCelebrating(true);setResult(true);setSelected(null);setMessage('Sealed. Your result is practice-only, not a leaderboard submission.');if(!loaded)return;
  const entry={id:puzzle.id,day,boxId,utilization:score},next=cleanHistory([...history.filter(r=>r.id!==puzzle.id),best&&best.utilization>score?best:entry]);setBusy(true);setStorage('Saving local result…');
  try{await runtime.storage.set(KEY,next);setHistory(next);setStorage('Local result saved');}catch{setStorage('Save failed. Your result is visible here but was not saved.');}finally{setBusy(false);}
 }
 const hintTarget=puzzle.witness[0],hintItem=puzzle.items.find(i=>i.id===hintTarget.id)!;
 function revealHint(){if(result||hintCount>=2)return;clock.begin();setHintCount(n=>Math.min(2,n+1));setMessage('Hint revealed. 20 seconds added to your scored time.');}
 const shareText=`Which Box? Daily Dispatch\n${puzzle.id} · ${score.toFixed(1)}% utilization · ${box.name} box\nPacked in ${formatTime(clock.elapsed)} · ${hintCount} hints (+${hintCount*HINT_PENALTY_SECONDS}s) · Scored time ${formatTime(scoredSeconds(clock.elapsed,hintCount))}\nLocal practice result, unverified. Same order for everyone on this UTC day.\n${runtime.playLabel} Can you use a smaller box?`;
 return <main><header><a className="wordmark" href="#" onClick={e=>{e.preventDefault();setTab('play');}}>WHICH BOX<span>?</span></a><span className="prototype">v1.2 / SINGLE PLAYER</span></header>
  <section className="headline"><div><span className="eyebrow">THE DAILY DISPATCH</span><h1>A little room.<br/><em>A little ingenuity.</em></h1><p>Today’s parcels. Your smallest possible box. Take your time, or beat it.</p></div><div className="date-stamp"><strong>{day}</strong><span>UTC EDITION · {puzzle.items.length} ITEMS</span><span>Resets 00:00 UTC / 05:30 IST</span></div></section>
  <nav aria-label="Sections">{[['play','Packing bench'],['rules','Fair-play rules'],['plan','The game plan']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</nav>
  {tab==='play'?<><div className="status-strip"><span><i/> {puzzle.id}</span><span>{best?`Your saved best: ${best.utilization.toFixed(1)}%`:'Your first dispatch starts here'}</span>{utcDay()!==day&&<button onClick={()=>reset(utcDay())}>Load today’s order</button>}</div>
   <section className={`clock-strip ${result?'clock-finished':''}`} aria-label="Packing timer"><div><span className="clock-label">{result?'PACKING TIME':clock.running?'ON THE BENCH':'READY WHEN YOU ARE'}</span><strong data-timer role="timer">{formatTime(clock.elapsed)}</strong></div><div className="clock-detail"><span data-penalty>{hintCount?`${hintCount} hint${hintCount===1?'':'s'} · +${hintCount*HINT_PENALTY_SECONDS}s`:'No hints used'}</span><strong data-scored>Scored time {formatTime(scoredSeconds(clock.elapsed,hintCount))}</strong></div><p>{result?'Lid closed. Nicely packed.':clock.running?'Undo is free. Every hint adds 20s.':'Timer starts with your first parcel or hint.'}</p></section>
   <div className="layout"><section className="workbench"><div className="bench-heading"><h2>01 / Choose your box</h2><span>Items stay put if they fit</span></div><div className="boxes">{puzzle.boxes.map(b=><button data-box={b.id} key={b.id} disabled={result} aria-pressed={b.id===boxId} onClick={()=>{const issue=validate(puzzle.items,b,ps);if(issue){setMessage('Unpack or rearrange before switching: '+issue);return;}setBoxId(b.id);setUndo([]);setCell([0,0]);}}><span className="box-symbol">{b.id}</span><span><strong>{b.name}</strong><small>{b.dims.join(' × ')}</small></span><span className="potential">{utilization(puzzle.items,b).toFixed(0)}%<small>if packed</small></span></button>)}</div>
    <div className="viewport"><div className="view-tools"><span>{result?'SEALED & READY':'DRAG TO ORBIT · SCROLL TO ZOOM'}</span><button data-view onClick={()=>setView(v=>v+1)}>{view%2?'Perspective':'Top view'}</button></div><Scene box={box} items={puzzle.items} placements={ps} preview={preview} valid={!error} view={view} sealed={result} skipAnimation={result&&!celebrating} onCell={(x,y)=>{setCell([x,y]);}}/><div className="volume-strip"><span><strong>{ps.length}</strong> / {puzzle.items.length} packed</span><div className="meter"><span style={{width:`${packedVolume/volume(box.dims)*100}%`}}/></div><span>{(packedVolume/volume(box.dims)*100).toFixed(1)}% filled</span></div></div>
    <div className="bench-actions"><button data-undo disabled={!undo.length||result} onClick={()=>{setPs(undo[undo.length-1]);setUndo(v=>v.slice(0,-1));setSelected(null);setMessage('Last placement undone.');}}>↶ Undo</button><button data-clear disabled={!ps.length||result} onClick={()=>{commit([]);setSelected(null);}}>Unpack all</button><button data-hint disabled={result||hintCount>=2} onClick={revealHint}>{hintCount>=2?'Both hints revealed':hintCount===1?'Placement hint · +20s':'Orientation hint · +20s'}</button></div>
    {hint&&!result&&<div className="hint" key={hintCount}><strong>{hintCount===1?'A useful first orientation':'Where to begin'}</strong><p>For a fresh compact-box arrangement, start with {hintItem.name}, oriented {hintTarget.dims.join(' × ')} (width × depth × height).{hintCount>1&&` Place it at column ${hintTarget.at[0]+1}, row ${hintTarget.at[1]+1}, on the floor.`}</p><small>This is one solution’s starting move. Your existing arrangement may need changing. Revealed hints stay visible without another penalty.</small></div>}
   </section><aside><h2>02 / Pack the order</h2><p className="subtle">Select a parcel. Packed parcels can be moved.</p><div className="items">{puzzle.items.map(i=><button data-item={i.id} key={i.id} disabled={result} aria-pressed={selected===i.id} onClick={()=>pick(i.id)} style={{'--item-color':i.color} as CSSProperties}><span className="swatch"/><span><strong>{i.name}</strong><small>{i.dims.join(' × ')} units</small></span><span className="packed">{ps.some(p=>p.id===i.id)?'✓':'+'}</span></button>)}</div>
    <div className="placement"><div className="placement-title"><strong>{item?item.name:'Pick an item to begin'}</strong><button data-rotate disabled={!item||result} onClick={()=>setOrientation(v=>(v+1)%os.length)}>↻ Rotate</button></div><p>{dims?`${dims.join(' × ')} · width × depth × height`:'All parcels can rotate in 90° steps.'}</p><div className="position-pad" style={{gridTemplateColumns:`repeat(${box.dims[0]},1fr)`}} aria-label="Placement grid, top view">{Array.from({length:box.dims[0]*box.dims[1]},(_,n)=>{const x=n%box.dims[0],y=Math.floor(n/box.dims[0]);return <button key={n} data-cell={`${x},${y}`} disabled={!item||result} aria-label={`Column ${x+1}, row ${y+1}`} aria-pressed={cell[0]===x&&cell[1]===y} onClick={()=>setCell([x,y])}>{ps.filter(p=>x>=p.at[0]&&x<p.at[0]+p.dims[0]&&y>=p.at[1]&&y<p.at[1]+p.dims[1]).length||'·'}</button>;})}</div><p className="subtle">Grid sets the top-left footprint corner. Numbers show stacked parcels. Height is automatic.</p><div className="place-actions"><button data-remove disabled={!selected||!ps.some(p=>p.id===selected)||result} onClick={remove}>Remove</button><button data-place className="secondary" disabled={!preview||!!error||result} onClick={place}>Place item{preview?` · level ${preview.at[2]+1}`:''}</button></div>{preview&&error&&<p className="invalid">{error}</p>}</div>
   </aside></div>
   <div className="dispatch"><p role="status" aria-live="polite">{message}</p>{!result?<button data-seal className="primary" disabled={!complete(puzzle,box,ps)||busy} onClick={seal}>Seal & ship <span>↗</span></button>:<button data-retry className="primary" disabled={busy} onClick={()=>{setResult(false);setCelebrating(false);clock.begin();setShare(false);setMessage('Try a smaller box or a new arrangement.');}}>Keep improving <span>↗</span></button>}</div>
   {result&&<section className="result" data-result><div className={`dispatch-stamp ${celebrating?'stamping':''}`} aria-hidden="true">PACKED & READY</div><span className="eyebrow">DISPATCH COMPLETE · LOCAL PRACTICE</span><h2>{formatTime(clock.elapsed)}<small>packing time</small></h2><div className="result-stats"><span><strong>{score.toFixed(1)}%</strong> utilization</span><span><strong>+{hintCount*HINT_PENALTY_SECONDS}s</strong> hint penalties</span><span><strong>{formatTime(scoredSeconds(clock.elapsed,hintCount))}</strong> scored time</span></div><p>{score===100?'A perfect fit. Every cubic unit put to work.':'Everything fits. Could a smaller box do the job?'}</p><p>{hint?`${hintCount} hint${hintCount===1?'':'s'} used.`:'Solved without hints.'} Time is for your own challenge, not an online rank.</p>{celebrating&&<button className="skip-celebration" onClick={()=>setCelebrating(false)}>Skip celebration</button>}<button data-share onClick={()=>setShare(!share)}>Show share card</button>{share&&<><ResultShare day={day} puzzleId={puzzle.id} utilization={score} boxName={box.name} hint={hint} elapsedSeconds={clock.elapsed} hintCount={hintCount}/><label htmlFor="share">Select and copy this spoiler-free result. Nothing is posted automatically.</label><textarea id="share" readOnly value={shareText} onFocus={e=>e.target.select()}/></>}</section>}
  </>:tab==='rules'?<article><span className="eyebrow">A LEVEL PACKING BENCH</span><h2>One day. One identical order.</h2><p>All players on this rules version get the same items, dimensions and box options for a given UTC date. Your level and history never change the daily puzzle.</p><h3>Your clock, your challenge</h3><p>The timer starts with the first selected parcel or hint and stops when you seal. Each of two optional hints adds 20 seconds to scored time. Re-reading a revealed hint costs nothing. Undo and camera changes are free. The timer continues in background tabs; reviewing a completed result is untimed. Keep improving resumes your clock and keeps hint penalties. Times reset on reload and are session-only; saved best utilization is unchanged.</p><h3>Utilization, explained</h3><p>Item volume divided by the chosen box’s internal volume. A valid complete packing is required. Time is a personal challenge. There is no countdown, no points penalty for undo, and no leaderboard.</p><h3>3D rules</h3><p>Whole-unit positions. Six possible dimension orientations. No overlaps, protruding parcels or floating items. Each parcel needs full support. Remove upper items before their supports. Placement drops vertically from above; no sliding through other parcels.</p><h3>What is local today</h3><p>This single-player release uses your device clock. It has no authoritative daily service, public leaderboard or identity verification. Results and best scores are unverified. At most 30 daily best results are kept locally; unfinished arrangements reset when closed.</p><h3>What comes next</h3><p>Better daily puzzles and simpler packing controls come first. Sharing is optional, and the result image never reveals your arrangement.</p></article>:<article><span className="eyebrow">FROM PLAYTEST TO DAILY HABIT</span><h2>Make the packing feel worth sharing.</h2><ol className="roadmap"><li><strong>01 / Prove the feel</strong><p>Watch new players rotate, stack and recover from mistakes. Improve controls before adding competition.</p></li><li><strong>02 / Earn each puzzle</strong><p>Build a curated catalogue with proven solutions, measured difficulty and repeat detection. This prototype partitions a box into solvable pieces; it does not guarantee endless novelty.</p></li><li><strong>03 / Make it effortless</strong><p>Keep improving touch, rotation and placement until the game needs no explanation. Competition features can wait.</p></li><li><strong>04 / Give people a reason to return</strong><p>Career levels, consensual challenge sharing and post-close solution replays. No unsolicited messages or punitive streaks.</p></li></ol><p className="hint">Not built yet: career progression, online rankings, cross-device saves and production puzzle deduplication.</p></article>}
  <footer><span>{storage}</span><span>Fictional product sizes · Rules dd-1 · No external services</span></footer>
 </main>;
}
